version: '3.8'

services:
  backend:
    build: ./fahrwerk-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork

  frontend:
    build: ./fahrwerk-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
